name: New Depends on wrkflow action

on: [workflow_dispatch, push]

jobs:
  git-clone:
    runs-on: ubuntu-latest
    steps:
     - name: clone the repository
       uses: actions/checkout@v3
  node-install:
    runs-on: ubuntu-latest
    steps:
     - name: setup node
       uses: actions/setup-node@v4
       with:
        node-version: 18
